167 renaming items
HackGT/timber pull request #174
Opened 2023-07-17 01:07 UTC by hgutha

Added a "What's this" text next to wherever a category or category group existed that opened a chakra ui alert explaining the difference categories and category groups.

2023-07-26 03:55 UTC, Roshan-D requested changes
I like it! Only thing I would say is just do away with the modal thing and have the alerts always visible just so it's easier for people to see when they are setting up expo in the future

2023-07-26 03:58 UTC, Roshan-D requested changes

2023-07-26 03:58 UTC, Roshan-D commented on src/components/projectGallery/ProjectCard.tsx
> +// import { InfoIcon } from "@chakra-ui/icons";
remove this

2023-07-26 03:58 UTC, Roshan-D commented on src/components/admin/AdminContentList.tsx
> +            {/* <AlertTitle>Information</AlertTitle> */}
get rid of all these other commented things also

2023-07-31 17:49 UTC, ayush-goyal requested changes

2023-07-31 17:49 UTC, ayush-goyal commented on src/components/projectGallery/ProjectCard.tsx
> +          </Flex>
I think we should remove the "What is this" from this page. There are so many texts that it makes it distracting. I think having the explanation just on the admin page is enough and we don't need anything here.
<img width="1471" alt="Screenshot 2023-07-31 at 1 47 30 PM" src="https://github.com/HackGT/timber/assets/8273038/bbf0d190-a9d8-4b63-b0b4-507f628ff8c7">

2023-07-31 17:49 UTC, ayush-goyal commented on src/components/projectStatus/ProjectTableContainer.tsx
> +                      What is this?
Same for the rest of the "What is this" 
<img width="360" alt="Screenshot 2023-07-31 at 1 48 23 PM" src="https://github.com/HackGT/timber/assets/8273038/103b36c0-a3e9-4253-8ab6-c92da697e8dd">

2023-07-31 17:49 UTC, ayush-goyal commented on src/components/admin/AdminContentList.tsx
> +      )}
I think keeping this here is enough. Everything else would be a little too much.

2023-08-11 17:46 UTC, Roshan-D requested changes
A lot of old code can be removed, see my comment. Also, can you make the text a Chakra UI banner so it's harder to miss?

<img width="1179" alt="Screenshot 2023-08-11 at 10 46 12 AM" src="https://github.com/HackGT/timber/assets/38771624/286a3143-1b96-4886-8ae0-37a9d62bbf8f">

2023-08-11 17:46 UTC, Roshan-D commented on src/components/admin/AdminContentList.tsx
> +  const [isOpen, setIsOpen] = useState(true);
all of these can be removed since we are now just always showing the description.

2023-08-14 06:43 UTC, Roshan-D approved these changes
nice!

2023-08-14 06:43 UTC, merged