Show Winners Toggle
HackGT/timber pull request #189
Opened 2023-08-22 20:38 UTC by nicolas-cai

- Created a toggle in the admin config panel to determine whether or not winners are shown to the public in the project gallery route
- Currently, project gallery toggles between the default view (no winners shown) and directly using the Winners component to represent the winners view (please let me know if there is a better way of doing this btw)
- Toggle vs Untoggled:
![image](https://github.com/HackGT/timber/assets/31454324/70a20fed-9c52-4384-a7c9-cf84bb45342b)
![image](https://github.com/HackGT/timber/assets/31454324/6914c75d-1dcd-4b17-b9b7-cfcb38886c97)

2023-08-28 22:07 UTC, nicolas-cai commented
This is what the newly published winners look like in the gallery. There's a tooltip icon overlayed on a winner banner that contains the rank, category, and members for the winning projects. Winners are filtered to appear at the top and separated visually from the other projects. Lmk if there's anything else I should change/add: 
![image](https://github.com/HackGT/timber/assets/31454324/12742439-ee11-4603-9de6-b15fa5f4b566)

2023-08-29 16:21 UTC, Roshan-D requested changes
Couple nits:

- The Emerging rank exists but isn't accounted for in the colors enum in `ProjectCard`
<img width="321" alt="Screenshot 2023-08-29 at 12 12 58 PM" src="https://github.com/HackGT/timber/assets/38771624/72dbd2a3-1654-4a5d-b3ed-5cde921d5fba">

- Might be cool if we also show the colors in the actual `ProjectCard` so you don't have to hover over the tooltip to see the rank

2023-08-29 16:35 UTC, nicolas-cai commented
> Couple nits:
> 
> * The Emerging rank exists but isn't accounted for in the colors enum in `ProjectCard`
> 
> <img alt="Screenshot 2023-08-29 at 12 12 58 PM" width="321" src="https://user-images.githubusercontent.com/38771624/264084782-72dbd2a3-1654-4a5d-b3ed-5cde921d5fba.png">
> * Might be cool if we also show the colors in the actual `ProjectCard` so you don't have to hover over the tooltip to see the rank

Would smth like this work? 
![image](https://github.com/HackGT/timber/assets/31454324/9c23febb-0ea0-4fa9-b34a-1880394e5b00)

2023-08-29 18:01 UTC, Roshan-D approved these changes
good stuff!

2023-08-29 18:01 UTC, merged